apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize


helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "7.3.11"
    releaseName: grafana
    valuesFile: values.yaml
    namespace: kustomize
