apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: kustomize
  annotations:
    avp.kubernetes.io/path: "/kv-v2/data/grafana"
type: Opaque
stringData:
  admin-password: "<admin-password>"
  admin-user: "<admin-user>"
  ldap-toml: "<ldap-toml>"
