apiVersion: v1
kind: Secret
metadata:
  name: testsec
  namespace: test-argocd 
  annotations:
    avp.kubernetes.io/path: "glowing-spoon/data/config"
type: Opaque
stringData:
  username: "<username>"
