apiVersion: v1
kind: Secret
metadata:
  name: glowing-spoon-secret
  namespace: new-test-argocd 
  annotations:
    avp.kubernetes.io/path: "glowing-spoon/data/config"
type: Opaque
stringData:
  username: "<username>"
