apiVersion: v1
kind: Secret
metadata:
  name: grafana2
  namespace: test-argocd 
  annotations:
    avp.kubernetes.io/path: "glowing-spoon/data/config"
type: Opaque
stringData:
  admin-password: "<password>"
  admin-user: "<admin-user>"
