apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "7.3.11"
    releaseName: grafana
    valuesFile: values.yaml
    namespace: kustomize

patches:
  - target:
      group: apps/v1
      version: v1
      kind: Secret
      name: grafana
    patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana
        namespace: kustomize
        annotations:
          avp.kubernetes.io/path: "/kv-v2/data/grafana"
    type: Opaque
    stringData:
      admin-password: "<admin-password>"
      admin-user: "<admin-user>"
      ldap-toml: "<ldap-toml>"
